fail test innit

diff --git a/.github/workflows/workflow1.yaml b/.github/workflows/workflow1.yaml
--- a/.github/workflows/workflow1.yaml
+++ b/.github/workflows/workflow1.yaml
@@ -20,6 +20,10 @@ jobs:
       # Check out your repository
       - uses: actions/checkout@v4
 
-      # Run a one-line script
+      # This step is intentionally made to fail
+      - name: To Show Error
+        run: echo "Should fail at this point ..." ; exit 1
+
+      # This step won't run if the previous one fails
       - name: Run a one-line script
         run: echo "Continuous Integration"
